// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	Office_desk_Observe = 0,
	Office_papers_Observe = 1,
	Office_cabinet_Observe = 2,
	Office_chair_Observe = 3,
	Office_bookshelf_Observe = 4,
	Office_drinks_Observe = 5,
	Office_typewriter_Observe = 6,
	Office_cabinet2_Observe = 7,
	Office_shelf_Observe = 8,
	Office_licence_Observe = 9,
	Office_bulletin_Observe = 10,
	Office_door_Observe = 11,
	Office_carpet_Observe = 12,
	Office_window_Observe = 13,
}
